### ISSUE TITLE
orbcat can't be used with grep

### ISSUE THREAD

**Issue by karlp** [mubes/orbuculum#6]
This doesn't work, it seems to be waiting for the end of input or something.
```
orbcat -c 0,'%c' | grep blah
```

**Comment by mubes** [comment]
I think this will be due to orbcat buffering. Try switching off the buffering with something like;

stdbuf -i0 -o0 -e0 orbcat....

Orbcat should perhaps flush stdout frequently, but that will slow it down so it should be a command line option.

**Comment by mubes** [comment]
I have added a flush to orbcat (which brings it into line with commands like tail -f etc). Please give it a go and see if it fixes this issue.  If so then we can close it down.

**Comment by mubes** [comment]
OK, this Works For Me and has been pending for two weeks, so I'm calling and closing it.

**Comment by karlp** [comment]
sorry, thought I'd already replied to this one! works for me too.
